### Element endpoints
GET http://127.0.0.1:3000/tools/bottom-text-bar HTTP/1.1
### API endpoints
GET http://127.0.0.1:3000/api/bottom-text-bar HTTP/1.1
###
POST http://127.0.0.1:3000/api/bottom-text-bar HTTP/1.1
Content-Type: application/json

{
  "SETTING_NAME": "Deneme1",
  "MAIN_TEXT":" deneme",
  "BACKGROUND_COLOR_CODE": "FFFFFF00"
}
###
PUT http://127.0.0.1:3000/api/bottom-text-bar/Deneme1 HTTP/1.1
Content-Type: application/json

{
  "MAIN_TEXT":" deneme2",
  "BACKGROUND_COLOR_CODE": "FFFFFF00"
}
###
DELETE http://127.0.0.1:3000/api/bottom-text-bar/Deneme1 HTTP/1.1
Content-Type: application/json
